services:
  - type: web
    name: ukmla-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn UKMLACaseBasedTutor7Cloud_FastAPI:app --host 0.0.0.0 --port $PORT --workers 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    plan: starter
    scaling:
      minInstances: 2
      maxInstances: 10
      targetConcurrency: 100 